### ISSUE TITLE
Importing from Sonarr not working

### ISSUE THREAD

**Issue by gitpowershelluser** [deathbybandaid/tdarr_inform#11]
Hi, thanks for this app it's exactly what I needed for my use case
Sab places the files Y:\Downloads\complete\tv
Tdarr monitors that folder and the cache location is Y:\TDarr\Cache
Final dest is E:\ShowName
Being able to process these items on my NVME would be a dream!

All of this appears to be normal, however tbey just sit there in the complete folder 

I didnt catch the cache folder there the first time and when i added the tdarr cache they started moving to the final location.  

I added an entire series and some of the files were picked up while the majority passed to their final dir 

The logs folder has this for each file 

[2023-02-26 18:49:03,061] INFO - Loading  tdarr_inform v0.3
[2023-02-26 18:49:03,061] INFO - Importing Core config values from Configuration File: Y:\Tools\tdarr_inform-master\config.ini
[2023-02-26 18:49:03,062] INFO - tdarr_inform called with custom_script mode
[2023-02-26 18:49:03,062] INFO - tdarr_inform Recieved Download Event from sonarr
[2023-02-26 18:49:03,062] INFO - Event Item: D:\Carnival Row (2019)\Season 01\Carnival Row (2019) - S01E01 - Some Dark God Wakes.mkv
[2023-02-26 18:49:03,062] INFO - Searching tdarr API for item's library ID
[2023-02-26 18:49:03,069] ERROR - No exact match found, searching for library ID from Reverse Recursive Directory matching
[2023-02-26 18:49:03,074] ERROR - No match found for D:\Carnival Row (2019)\Season 01\Carnival Row (2019) - S01E01 - Some Dark God Wakes.mkv
[2023-02-26 18:49:03,074] ERROR - No matches found, Exiting

The config looks like this 

[logging]
level = INFO
format = None

[main]
cache_dir = Y:\TDarr\Cache

[tdarr]
address = localhost
port = 8265
ssl = None

Tdarr v.18 (.19 does not work on my PC)
Using QVC to encode the files 
1 transcode on the GPU
1 health check on the CPU
Using windows installation for all the webapps

**Comment by deathbybandaid** [comment]
Is your tdarr on the same machine as sonarr?

**Comment by gitpowershelluser** [comment]
Yes all on the same internal NVME drive

**Comment by deathbybandaid** [comment]
The script uses the tdarr api to try and find the tdarr library that would have the file into it's path.

**Comment by gitpowershelluser** [comment]
Some of the files are being prossesed, others are not
I made no changes and sent another series through and it sent 0 files through Tdarr this time

**Comment by deathbybandaid** [comment]
I'm seeing multiple drive letters here. D,E,Y

Side note the main/cache_dir has nothing to do with tdarr's cache directory

**Comment by gitpowershelluser** [comment]
D should be E - my apolpogies both are external drives for my content one for series, one for movies.
What is this directory?  main/cache_dir

**Comment by deathbybandaid** [comment]
Just internal logs and stuff for the script

**Comment by deathbybandaid** [comment]
So `D:\Carnival Row (2019)\Season 01\Carnival Row (2019) - S01E01 - Some Dark God Wakes.mkv` 

would start by checking if tdarr has an exact path match

It then checks if tdarr can match the tdarr library id from the season drectory

Then the show directory.

It might be getting hung up with the show folder being the root of the drive.

Let me push code to a test branch

**Comment by deathbybandaid** [comment]
theory looks to be correct. I have a coded check for drive root path

**Comment by gitpowershelluser** [comment]
D: is final destination
Y: is where the file should be until it's completd.  Please help me with the logic real quick
Sonarr searches file and sends match to > Sab downloads it, unpacks it and an call is made back to > Sonarr to run script and hold file so > Tdarr can process the file the finally back to > Sonarr for proper naming and move to final destination

**Comment by deathbybandaid** [comment]
In Tdarr, you create libraries at a specific path. Tdarr then monitors that directory for changed files, and processes them when it detects a change.

Without tdarr_inform, Tdarr depends on filesystem events, or directory scanning to import files.

tdarr_inform just gets tdarr to check the file paths from sonarr as soon as possible.

Sonarr is telling Tdarr about the final destination. This script is called after Sonarr moves the file.

**Comment by gitpowershelluser** [comment]
I hate to say this, but that is not happening on MY pc.. for exmaple

I just downloaded season 5 and season 6 of a series
season 6 passed completely through to the final destination on E:
Season 5 is being processed by tdarr on Y:

**Comment by deathbybandaid** [comment]
In Tdarr, there are 2 directories that can be set for a library.

The "Source" directory, which should be the final destination for files to be, and a "Transcode cache" directory, which is just a directory for tdarr to place files temporarily while they are being processed.

**Comment by deathbybandaid** [comment]
Were you using Tdarr prior to using tdarr_inform? I'm not sure how you would have tdarr process a file between Sab downloading and Sonarr moving?

**Comment by deathbybandaid** [comment]
Pushed #12 to help with users that have Tdarr Libraries at drive roots. Which may not even impact your setup.

**Comment by gitpowershelluser** [comment]
yes, for awhile now
never been able to process files in between sab and sonarr and based off the last sentence in the readme
'allows for Tdarr to convert new media prior to an end-user streaming content from your media server.'

I assumed this would be the ticket I needed

**Comment by gitpowershelluser** [comment]
> Pushed #12 to help with users that have Tdarr Libraries at drive roots. Which may not even impact your setup.

testing

**Comment by deathbybandaid** [comment]
maybe I'll have to rephrase the readme a bit. In my use-case, (and others that use this script), the media server usually doesn't know about the changed file prior to tdarr processing it.

tdarr_inform might not suit your use-case, as you are running your services from the same windows machine, and your services are able to get filesystem events.

tdarr_inform is mostly used for applications that run on separate servers from a storage-server/NAS with files shared with SMB/CIFS (doing so doesn't supply applications with filesystem events.)

**Comment by deathbybandaid** [comment]
Updated the readme to potentially be less confusing

**Comment by gitpowershelluser** [comment]
Ah, would make sense for this script :)  I'm really looking for a solution
And the updated version doesn't work for me

**Comment by deathbybandaid** [comment]
What is your Tdarr library path that an example file should match

Keep in mind this is the path that Sonarr puts the file

**Comment by gitpowershelluser** [comment]
My root folder is D:

"D:\Carnival Row (2019)\Season 01\Carnival Row (2019) - S01E01 - Some Dark God Wakes.mkv"

**Comment by deathbybandaid** [comment]
`D:\` is the Tdarr library path?

Can I see a log from sonarr with the new changes?

**Comment by gitpowershelluser** [comment]
yes One Minute, I want to find a new show 

Oh I'm sorry
The tdarr path is not set to D:\, it's set to Y:\downloads\complete\tv

**Comment by deathbybandaid** [comment]
That's the problem then. Sonarr tells tdarr_inform a path on `D:`, tdarr_inform checks with Tdarr for a library match on `D:`, but will never find a match when the Tdarr library path is on `Y:`.

**Comment by gitpowershelluser** [comment]
Going to need a few more moments for full logs.  It picked up a second episode and I want to provide them

**Comment by gitpowershelluser** [comment]
The first file it processed normally - however I went into sonarr, found something and then requested an indiviual file
The second, sonarr picked up as missing but you'll see errors.  It did two things unpacked the file and then sent it to the final destination but TDARR also picked it up
https://pastebin.com/raw/FyphvFnL

**Comment by gitpowershelluser** [comment]
This was in sab 
 Error renaming "Y:\Downloads\complete\tv\_UNPACK_The.Last.of.Us.S01E07.Left.Behind.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb" to "Y:\Downloads\complete\tv\The.Last.of.Us.S01E07.Left.Behind.1080p.AMZN.WEB-DL.DDP5.1.H.264-NTb"

**Comment by gitpowershelluser** [comment]
2023-02-26 22:38:54.3|Info|SeriesSearchService|Series search completed. 1 reports downloaded.
2023-02-26 22:38:55.3|Info|SceneMappingService|Updating Scene mappings
2023-02-26 22:38:56.8|Info|RefreshSeriesService|Updating The Simpsons
2023-02-26 22:38:58.2|Info|RefreshEpisodeService|Starting episode info refresh for: [71663][The Simpsons]
2023-02-26 22:38:58.5|Info|RefreshEpisodeService|Finished episode refresh for series: [71663][The Simpsons].
2023-02-26 22:38:58.5|Info|DiskScanService|Scanning The Simpsons
2023-02-26 22:38:59.7|Error|python.exe|[2023-02-26 22:38:59,795] INFO - Loading  tdarr_inform v0.3
2023-02-26 22:38:59.7|Error|python.exe|[2023-02-26 22:38:59,795] INFO - Importing Core config values from Configuration File: Y:\Tools\tdarr_inform-master\config.ini
2023-02-26 22:38:59.7|Error|python.exe|[2023-02-26 22:38:59,796] INFO - tdarr_inform called with custom_script mode
2023-02-26 22:38:59.7|Error|python.exe|[2023-02-26 22:38:59,796] INFO - tdarr_inform Recieved EpisodeFileDelete Event from sonarr
2023-02-26 22:38:59.7|Error|python.exe|[2023-02-26 22:38:59,796] INFO - Event Item: D:\The Simpsons (1989)\Season 34\The Simpsons (1989) - S34E14 - Carl Carlson Rides Again.mkv
2023-02-26 22:38:59.7|Error|python.exe|[2023-02-26 22:38:59,796] INFO - Searching tdarr API for item's library ID
2023-02-26 22:38:59.8|Error|python.exe|[2023-02-26 22:38:59,807] ERROR - No exact match found, searching for library ID from Reverse Recursive Directory matching
2023-02-26 22:38:59.8|Error|python.exe|[2023-02-26 22:38:59,809] ERROR - No match found for D:\The Simpsons (1989)\Season 34\The Simpsons (1989) - S34E14 - Carl Carlson Rides Again.mkv
2023-02-26 22:38:59.8|Error|python.exe|[2023-02-26 22:38:59,810] ERROR - No matches found, Exiting
2023-02-26 22:38:59.8|Error|python.exe|Traceback (most recent call last):
2023-02-26 22:38:59.8|Error|python.exe|  File "Y:\Tools\tdarr_inform-master\tdarr_inform.py", line 24, in <module>
2023-02-26 22:38:59.8|Error|python.exe|    sys.exit(run.main(SCRIPT_DIR))
2023-02-26 22:38:59.8|Error|python.exe|             ^^^^^^^^^^^^^^^^^^^^
2023-02-26 22:38:59.8|Error|python.exe|  File "Y:\Tools\tdarr_inform-master\Tdarr_Inform\cli\run.py", line 142, in main
2023-02-26 22:38:59.8|Error|python.exe|    return start(args, script_dir)
2023-02-26 22:38:59.8|Error|python.exe|           ^^^^^^^^^^^^^^^^^^^^^^^
2023-02-26 22:38:59.8|Error|python.exe|  File "Y:\Tools\tdarr_inform-master\Tdarr_Inform\cli\run.py", line 113, in start
2023-02-26 22:38:59.8|Error|python.exe|    return run(args, settings, logger, script_dir, versions, web)
2023-02-26 22:38:59.8|Error|python.exe|           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2023-02-26 22:38:59.8|Error|python.exe|  File "Y:\Tools\tdarr_inform-master\Tdarr_Inform\cli\run.py", line 64, in run
2023-02-26 22:38:59.8|Error|python.exe|    Tdarr_Inform.handlers.CustomScript(settings, logger, web)
2023-02-26 22:38:59.8|Error|python.exe|  File "Y:\Tools\tdarr_inform-master\Tdarr_Inform\handlers\custom_script\__init__.py", line 37, in __init__
2023-02-26 22:38:59.8|Error|python.exe|    raise Exception("No matches found, Exiting")
2023-02-26 22:38:59.8|Error|python.exe|Exception: No matches found, Exiting
2023-02-26 22:38:59.8|Info|DiskScanService|Completed scanning disk for The Simpsons
2023-02-26 22:38:59.8|Info|ExistingMetadataImporter|Found 0 existing metadata files
2023-02-26 22:38:59.8|Info|ExistingSubtitleImporter|Found 0 existing subtitle files
2023-02-26 22:38:59.8|Info|ExistingOtherExtraImporter|Found 0 existing other extra files
2023-02-26 22:38:59.8|Info|ExistingExtraFileService|Found 0 possible extra files, imported 0 files.

**Comment by deathbybandaid** [comment]
> That's the problem then. Sonarr tells tdarr_inform a path on `D:`, tdarr_inform checks with Tdarr for a library match on `D:`, but will never find a match when the Tdarr library path is on `Y:`.

This is your problem still. It will never find the Sonarr path when your tdarr path isn't the same

**Comment by gitpowershelluser** [comment]
Not really a problem I guess, just not working as you designed it

**Comment by gitpowershelluser** [comment]
Is there a way to update the script ala buy you  gallons worth of coffee?

**Comment by deathbybandaid** [comment]
I don't see a way to accomplish what you are trying to do.

You would need a different script alltogether for sab to post-process before the handoff to sonarr. Even then, the tdarr library would have to be your download directory which would be dangerous.

Tdarr just doesn't work in the chain the way you want.
Here's a different project which I think does more of what you want.
https://github.com/mdhiggins/sickbeard_mp4_automator

Tdarr manages libraries, not really one-off paths.

**Comment by gitpowershelluser** [comment]
I appreacite the effort.
