### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by sbcrumb** [deathbybandaid/tdarr_inform#21]
Both my tdarr and sonarr are dockers.

2023-11-06 10:39:02.0|Error|tdarr_inform.py|Traceback (most recent call last):
2023-11-06 10:39:02.0|Error|tdarr_inform.py|  File "/scripts/tdarr_inform/tdarr_inform.py", line 19, in <module>
2023-11-06 10:39:02.0|Error|tdarr_inform.py|    from Tdarr_Inform.cli import run
2023-11-06 10:39:02.0|Error|tdarr_inform.py|  File "/scripts/tdarr_inform/Tdarr_Inform/cli/run.py", line 11, in <module>
2023-11-06 10:39:02.0|Error|tdarr_inform.py|    import Tdarr_Inform.web
2023-11-06 10:39:02.0|Error|tdarr_inform.py|  File "/scripts/tdarr_inform/Tdarr_Inform/web/__init__.py", line 1, in <module>
2023-11-06 10:39:02.0|Error|tdarr_inform.py|    import requests
2023-11-06 10:39:02.0|Error|tdarr_inform.py|ModuleNotFoundError: No module named 'requests'

Output of the requirement install
pip3 install -r requirements.txt
Requirement already satisfied: requests in /usr/local/lib/python3.10/dist-packages (from -r requirements.txt (line 1)) (2.28.1)
Requirement already satisfied: charset-normalizer<3,>=2 in /usr/local/lib/python3.10/dist-packages (from requests->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (3.3)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (1.26.5)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from requests->-r requirements.txt (line 1)) (2020.6.20)

Any idea what is causing this?

**Comment by deathbybandaid** [comment]
did you do the pip install within your docker container for sonarr?

**Comment by sbcrumb** [comment]
Tried but it is not available, I am using hotio's sonarr and radarr.

**Comment by deathbybandaid** [comment]
I'm not a docker user, so I'm not sure how you would go about getting it setup within the docker container. Since Sonarr runs the script, sonarr's environment needs to have the dependency.

**Comment by sbcrumb** [comment]
Thanks I got this working.. I will close and open another issue I am having.
